syntaxt issue fixed

diff --git a/.github/workflows/log_check.yml b/.github/workflows/log_check.yml
--- a/.github/workflows/log_check.yml
+++ b/.github/workflows/log_check.yml
@@ -13,12 +13,13 @@ jobs:
 
       - name : Print hello.txt contents
         run: |
-          if [ -f "hello.txt"]; then
-            echo "---- hello.txt ----"
-            cat hello.txt
-            echo "--------"
-          else 
-            echo "hello.txt not found" && exit 1
-          fi
+            if [ -f "hello.txt" ]; then
+              echo "---- hello.txt ----"
+              cat hello.txt
+              echo "--------"
+            else
+              echo "hello.txt not found"
+              exit 1
+            fi
 
 
